### ISSUE TITLE
Data attribute not compiling properly 

### ISSUE THREAD

**Issue by CharlieGreenman** [snabbdom-jsx/snabbdom-jsx#11]
I have attached the following data attribute `data-type="column"` to my input tag  and it does not carry over. Can provide more details.

**Comment by ricochet1k** [comment]
Try `attrs-data-type` instead of `data-type`

**Comment by SteveALee** [comment]
I'm reopening as it's not working for me. Will create a now ticket if preferred. 

if have ` <div attrs-data-action='speak'>Wibble</div>`

i see this chrome dev tools
`<div data="[object Object]">Wibble</div>`

and the cyclejs select `sources.DOM.select('[data-action="speak"]')` fails

It previously worked fine when not using JSX 
We are using TS to compile the JSX in create-cycle-app

**Comment by SteveALee** [comment]
I just double checked and snabbdom without jsx is fine - and Chrome shows 
`<div data-action="speak"">Wibble</div>`
as expected.

For reference the non jsx code is
`div({dataset: {action: 'speak'}}, 'Wibble'),`

thanks

**Comment by SteveALee** [comment]
This may be as the create-cycle-app flavor uses [Typescript to do standard React JSX parsing](https://www.typescriptlang.org/docs/handbook/jsx.html). From what I can determine React CreateElement expects `'data'action: 'speak'`, the quotes being required due to the semicolon.

Can we figure this out somehow so? Are there mor differences between snabbdomjsx and react JSX that mean we cant use TypeScript React JSX parsing?

We can tell TypeScript to pass through the JSX and use a subsequent process, but we just removed bable to let typescript do all the work

**Comment by SteveALee** [comment]
Please close as this is nothing to do with snabbdom-jsx

Sorry!

**Comment by WorldMaker** [comment]
The dataset module should work in 0.3.2 (your example in JSX/TSX would be `dataset-action='speak'`).

I published my simplified Typescript typings in 0.4.0, which should lend a better Typescript experience moving forward.

(Both of these pieces I've been using for some time. I'm excited to get them published to npm finally.)

**Comment by SteveALee** [comment]
It does thanks!
