### ISSUE TITLE
`buildFromComponent` could accept a vnode-object and wrap it in a function...?

### ISSUE THREAD

**Issue by gnimmelf** [snabbdom-jsx/snabbdom-jsx#23]
Disclaimer: Almost newbie!

Just started testing `Cycle.js`, and following the [`JSX`  docs there](https://cycle.js.org/getting-started.html#getting-started-coding-consider-jsx), it annoyes me that I have to manually wrap the virtual nodes with functions to make them act as tag-components.

Could [`buildFromComponent`](https://github.com/yelouafi/snabbdom-jsx/blob/5c358839cb208bf76023ea2c0967091a52f9bc70/snabbdom-jsx.js#L62) just accept vnodes and wrap instead of throwing?

Cheers.

**Comment by WorldMaker** [comment]
I use Cycle as well, but I'm not sure I understand how you are trying to use components in JSX. Do you have an example repo you can point to of what you are trying to accomplish?

**Comment by WorldMaker** [comment]
Something related to my unfinished noodling about #18, maybe?

**Comment by gnimmelf** [comment]
Perhaps, I am not quite sure what you mean by thunks, but as a contrived example with snippets from the `cycle.js` documentation:

Given the `LabeledSlider.js` component, I'd like to use it in BmiCalculator.js as a "React component in pure jsx". 
```
import LabeledSlider from './LabeledSlider'
/* ... */
const weightSlider = isolate(LabeledSlider)({DOM: domSource$, props: weightProps$});
const heightSlider = isolate(LabeledSlider)({DOM: domSource$, props: heightProps$});
/* ... */
const vdom$ = xs.combine(state$, weightVDom$, heightVDom$)
    .map(([state, weightVDom, heightVDom]) => {
      // THIS `map` could be done automagically:
      return [state, () => weightVDom, () => heightVDom]
    })
    .map(([state, WeightSlider, HeightSlider]) =>
      <div className="calculator">
        <WeightSlider /> //
        <HeightSlider />
        <h2>{state.label} BMI is {state.bmi}</h2>
      </div>
    );
```
Now I just need another `.map` to wrap the `VDom`s in a function, or fake anything that `buildFromComponent` accepts. So can `buildFromComponent` accept a pure `VDom` object and wrap it, is what I am asking.

...and, looking at it again now, yes it's a thunk =)

Cheers!

**Comment by WorldMaker** [comment]
That does give me a better perspective of what you are looking for. The components I've built actually use the arguments to the component function for data passing and complex low-level Snabbdom stuff. An abbreviated example:

```ts
export function Graph({ data, layout }: any, children: any) {
    return <div hook={ { insert, postpatch, destroy } }
        dataset-data={ fromJS(data) }
        dataset-layout={ fromJS(layout) }>
    </div>
}

const exampleGraph = (state: any) => <Graph data={ state.dataSource } layout={ state.layoutInfo } />
```

In cases like your example I wouldn't be using JSX components and would just write it as:

```ts
import LabeledSlider from './LabeledSlider'
/* ... */
const weightSlider = isolate(LabeledSlider)({DOM: domSource$, props: weightProps$});
const heightSlider = isolate(LabeledSlider)({DOM: domSource$, props: heightProps$});
/* ... */
const vdom$ = xs.combine(state$, weightVDom$, heightVDom$)
    .map(([state, weightSlider, heightSlider]) =>
      <div className="calculator">
        { weightSlider } //
        { heightSlider }
        <h2>{state.label} BMI is {state.bmi}</h2>
      </div>
    );
```

(Thunks are snabbdom boundaries to keep from patching the contents as often by passing it a bit more state information that it checks for equality first. Cycle `isolate` sort-of auto-thunks. I could use auto-thunking for things like my `Graph` component.)

**Comment by gnimmelf** [comment]
Hmm...

Your last example is identical to the `cycle.js` documentation-example. For me the difference seems to be just the semantics of e.g `{ weightSlider }` vs `<WeightSlider />`. 

-So, are you saying is that there is a higher cost to using `<Component />`s due to vdom-diffing because the component is not assumed "pre-rendered" and static in the context, whereas a vdom object is?

`Snabbdom` is not a `cycle.js` exclusive, but sine that is my learning approach, I might be blindsided by that context.

Thanks.

**Comment by WorldMaker** [comment]
Sure, let's take a step back, ignore thunks as a low level detail and look at the overall philosophy. JSX components come from the React world. React components (despite or in spite of the name "React") follow a pull-model. It's up to a component to pull the information it needs. When a React JSX file use a `<Component />` it is doing everything necessary to setup/teardown that component and start that component's data pull.

CycleJS takes a much more push model: components "request" data from drivers and drivers push data as it becomes available. To wire in a new component you have to consider where its inputs should come from and where its outputs should go, in your consuming component's intent/model somewhere. By the time it gets to assembling that all into your components view, almost all of the work has already been done, almost all of the data has already arrived, you just plug it into the right holes in you view template and move on.

It might be better is CycleJS used a different name than "component" to differentiate the difference between what React is doing with its "component" model, they act quite differently.

Where I use JSX components in my Cycle app is for things like HTML macros/templates where I want to slot some other tags inside it somewhere (children) (and even then there's still a likelihood I may just use `{ templateViewFunction(attrs, <div>child</div>) }` directly unless it starts to get ugly/complicated looking), or things that have DOM "side effects" that I need to use snabbdom hooks to manage like setup/teardown of a graphing library, Leaflet map, or `URL.createObjectURL(blob)` and `URL.revokeObjectURL(blob)` management for building image `src` URLs from database Blobs.

`{ weightSlider }` is just a value at the point where that view is getting it. It doesn't have any more work to be done, nor any more side-effects that need to happen to the DOM. Other than aesthetics, is there a benefit you can see to being able to use the `<WeightSlider />` syntax? You can't give it attributes, because those should already be passed in the `weightProps$` observable; same with children. You can't really take advantage of the tag structure `<WeightSlider prop1="example"><span>Inside the slider</span></WeightSlider>`. You would also be signaling to me, from my project experience, that `<WeightSlider />` may have snabbdom/DOM side effects when that isn't the case.

(Though this does give me thoughts about you could build a JsxDriver for Cycle that could take advantage of those things, and maybe replace `weightProps$` with the source from that driver. I'm not sure useful that would be, though... and so far in the direction of most Cycle development wouldn't feel all that appropriate.)

**Comment by gnimmelf** [comment]
Excellent! 

`cycle.js` uses the term `dataflow component`, so I guess that is an attempt at differentiation while still keeping in touch with the component-buzz.

Other than that, I see what you mean now (although it will take me a fair bit of practice to grok it properly).

So thank you for the clarifications, really warms my heart that you took the time to write it out.

Feel free to close the issue.

**Comment by WorldMaker** [comment]
Glad I could help.
